title = "Infosec 101 for Activists"
relativeURLs = true
publishDir = "public"

# provides 'Last Modified' date
enableGitInfo = true

[markup.tableOfContents]
startLevel = 1
endLevel = 2

defaultContentLanguage = 'en'
[languages]
[languages.en]
contentDir = 'content/en'
languageName = 'English'
languageNameShort = 'En'
title = 'Infosec for Activists'
weight = 1

[languages.es]
contentDir = 'content/es'
languageName = 'Español'
languageNameShort = 'Es'
title = 'Infosec para Activistas'
weight = 2

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
BookTheme = 'auto'
BookComments = false
BookSection = "*"
BookSearch = false