baseURL = "https://infosecforactivists.org/"
title = "Infosec 101 for Activists"
theme = "book"

# provides 'Last Modified' date
enableGitInfo = true 

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 2
