baseURL = "https://preview.infosecforactivists.org/"
title = "Infosec 101 for Activists"
theme = "book"
relativeURLs = true

# provides 'Last Modified' date
enableGitInfo = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = 'English'
    languageNameShort = 'En'
    title = 'Infosec for Activists'
    weight = 1

  [languages.es]
    languageName = 'Spanish'
    languageNameShort = 'Es'
    title = 'Infosec para Activistas'
    weight = 2