---
title: "DRAFT Infosec 101 for Activists DRAFT"
author: "Drew Bjorn, Mark Sherman, Ph.D., and Blake Skinner"
date: 'Updated `r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# DRAFT

# Introduction

The United States has a strong tradition of activism, dating back to the Boston Tea Party. Today, activism in the US remains critical. That being said, challenging existing power structures carries an element of [risk](https://www.aclu.org/issues/free-speech/rights-protesters/anti-protest-bills-around-country); and your [personal information](https://www.businessinsider.com/fbi-uses-instagram-etsy-linkedin-to-find-george-floyd-protester-2020-6) is more accessible than it has ever been in the past. In this document, we’ll talk about how hostile groups can leverage information against activists, and what you can do to protect yourself and others.  

*If you are in a hurry, please begin with the tools chart below.*  You’ll find information you can use right away! We have also included tips and concepts to make your personal information safer at actions AND in your day to day life.

# Tools to Use

Need secure, private communications in a hurry?  Here are services you can switch to right now!  (We do not receive kickbacks from any of these companies.  Or anybody, actually.)


| Tools                                 | Use          | What it replaces, or what it does                                                    | What it costs                  |
|---------------------------------------|--------------|--------------------------------------------------------------------------------------|--------------------------------|
| [Signal](https://signal.org/en/)      | Messaging    | Text messages, facebook messenger, other insecure instant messaging apps             | Free                           |
| [Firefox](https://www.mozilla.org/en-US/firefox/new/)| Web Browsing  | Google Chrome, Safari, Internet Explorer, Edge                       | Free                           |
| [DuckDuckGo](https://duckduckgo.com/) | Web Searching| Google Search                                                                        | Free                           |
| [ProtonMail](https://protonmail.com/) | Email        | Gmail, yahoo, work email                                                             | Free for basic, ~$5/mo for more|
| [ProtonVPN](https://protonvpn.com/)   | VPN          | Protects your activity from your cable or mobile provider, who may share with police.| Free, with paid tiers for faster service and more devices|

# Things to Know
Your phone is a data goldmine, full of tracking and identifying information. This includes where you have been, what you have said, and who you have communicated with. This section will help you keep that data safe while you are attending a protest, keeping you AND those around you safer. Find instructions for iPhone and Android below! Get protected and protest ready right now!

Assume that any messages you send, phone calls that you make, or anything else you send or receive can be logged & recorded by the police. If your information is strongly encrypted, they may still have it, but can’t decrypt it. Be sure to update your phone to the latest supported OS well before the action.

If you have privacy concerns and your phone is no longer receiving software updates, consider not bringing it. If you are attending a protest without a phone, don’t go alone. Arrange times and places where you can meet up with your buddies, before you go to the protest.

## Do’s and Don’ts
* **Do not “check in” to a protest on Facebook** or any other service. You don’t want to give third parties evidence that you were there. Police use subpoenas to get user information from Facebook and other social media companies all the time.
* **Don’t post photos or videos.** These have extra information hidden in them that includes the time and place they were taken. If you send photos or videos out at all, only send them to people you trust, over secure means, long after and far away from the protest. 
* **Don’t take anyone’s photo without permission.** 
* **Do have a protest buddy and use Signal to communicate with them.**
* **Do write an emergency contact’s number somewhere conspicuous** (piece of paper, on your arm, etc) in case your device is confiscated or lost.  If you are at a high risk event, also bring the phone number of your local chapter of the [National Lawyer’s Guild](https://www.nlg.org/) (in case of arrest).
* **If you are using Signal or WhatsApp, enable “Disappearing Messages” for any sensitive conversations.**

# Attending an Action
## Before
* Do not mark yourself as “Going” on Facebook.
	* Make note of the details, and save them on a personal device or piece of paper.
* Practice your passcode. Enable and practice using [Emergency SOS](https://support.apple.com/en-us/HT208076) (iOS) and [Lockdown mode](https://support.google.com/pixelphone/answer/6093922#lockdown) (Android)
* If you need to search the internet for any information relating to the protest, use DuckDuckGo and private browsing sessions.
* Make sure your device is updated to the latest version of your OS, and all your apps are up to date.
	* Check and update your [Android](https://support.google.com/android/answer/7680439) or [iOS](https://support.apple.com/en-us/HT204204) version to make sure you have the latest security fixes. 
* Set up a [Signal](https://signal.org/en/) account. If you don’t want to use your personal phone number, you can create a new phone number with Google Voice and register that with Signal.
* Find a friend (or several!) to go with and connect over Signal to discuss plans.

## During
* Confirm meetup plans with your protest buddies before leaving for the event. 
	* Once you meet up, agree on a fallback location in case you get separated. 
* Use [Apple Maps](https://maps.apple.com/go) or [DuckDuckGo Maps](https://duckduckgo.com/) if you need directions to the location of the protest. 
	* If you can, print the directions. While Apple Maps does not have an explicit Offline mode, if you route to a location it will retain the directions and surrounding map data.

## After
* Leave & delete Signal groups set up for that protest. (The last one to leave burns the group.)
* Don’t post your protest photos on social media!

# Preparing your Phone
Your phone is a powerful tool, but also a powerful tracking device for law enforcement and other entities. Phones record and share lots of information about your whereabouts and activity with different services. This is usually a good thing, as it helps your apps respond to your needs and situation. But when you attend an action, those features can provide a rich digital breadcrumb trail. We want to prevent those digital breadcrumbs from being dropped, and here is some advice on how to do that.

Attending an action brings an additional threat to privacy. If your phone is lost or confiscated by law enforcement, all the information on it could then be available to police. Below we will share advice to make your phone as strong as possible against intrusion should it fall into someone else's hands. 

This section uses the word "phone" to mean a smartphone running iOS or Android, such as those manufactured by Apple, Google, Samsung, and others. If you are using a simpler phone, your risks are likely less. 

## Digital Breadcrumbs

Whether you have an iPhone or an Android, the threats to your privacy are the same. Your phone has a **GPS** reciever built into it that enables maps and other location-based apps to work. The phone itself will keep that GPS recieveer on at all times, recording where you are, and occasionally send updates on your whearabouts to Google, Apple, or other app publishers. So we will want to turn the GPS reciever off, which prevents from the location data from being recorded at all. 

**Bluetooth and WiFi** are common technologies that use short-range radio to communicate with other devices. Unfortunately, their operation requires your phone to broadcast identifiable information about itself. This information can be observed by a "beacon" or scanning device. Stores, government agencies, and police use these devices to identify people who are nearby. Companies have deployed Bluetooth beacons in their stores to identify how long customers linger in certain departments, or in front of certain displays, and then correlate that data with the person's other identifying information. This type of surveillance is profoundly dangerous at an action, so we need to disable Bluetooth and WiFi whenever possible. 

**Your mobile carrier** can track your location by when your phone contacts its radio towers. Phones connect to towers periodically while on, even if they are not being actively used. Towers connections are sufficiently accurate to place an individual on the same block as an action. This information can be accessible to law enforcement through a subpoena. This data is slightly  more difficult for law enforcement to get than Bluetooth or Wifi, but it can be done.

All phones have an option for **"airplane mode,"** which disables *all* radios. This feature was created for travel in an airplane, out of a concern that phones would interfere with the plane's operation. This feature is useful today for being a reliable way to disable all three radios with one button: WiFi, Bluetooth, and mobile carrier. There are some slight caveats, detailed below, of which the biggest is that airplane mode usually does not disable the GPS receiver. Generally, airplane mode is an important tool to prevent generation and collection of tracking data.

## Intrusion Protection

If you attend an action, there is a risk that your phone may be seized by police. They physically have your phone and may attempt to extract information from it. All phones have **lock screens**, which is the first line of defense. In day-to-day use, we want our lockscreen to be secure against a thief, or a taxi driver, or some other stranger, from easily opening the phone. With that, fingerprint readers and face scanners make for convenient unlock mechanisms. The situation at an action is starkly different, as law enforcement may have detained you with your phone, and therefore may have the ability to apply your finger or face to your phone to unlock it, even if you resist or are unconscious. For this reason, **biometric unlock mechanisms should be avoided during an action**. The other unlock mechanisms are typically drawing a shape or entering a code. **Entering a code is the most secure**, as the shape can be traced from fingerprints on the screen. The code should also be long enough to prevent your fingerprints from giving it away, too. Related, you want your screen to lock quickly on its own. The **power button should make the phone immediately lock**, so that you can lock it quickly. Phones also let you select how long they should wait before auto-locking themselves. This time should be as short as possible, so that if you drop your phone or if it is stolen, the timer will expire and the phone will lock before anyone else can access it. 

There are ways to access data on a phone without unlocking it. One way to defend against these methods is **full-disk encryption**, where all the information on the phone is stored encrypted. When the phone is turned on, nothing can be read until the screen is unlocked the first time, at which point it will decrypt information as needed, and continue to store information in encrypted form. This prevents law enforcement from removing the storage chips from your phone, as all of the contents will be unreadable without being unlocked in your specific phone. Luckily, this feature is turned on by default on most phones, so you probably don't have to worry about it! **If you have an older-model android** you may be able to turn on full-device encryption. This paragraph impacts phones that are running [Android versions lower than 6](https://www.computerworld.com/article/2995437/google-makes-full-disk-encryption-and-secure-boot-mandatory-for-some-android-60-devices.html), but it’s worth a check even if your phone is running 6 or higher. **Go to Settings, choose Security, and find the Encrypt Phone option.** It will say “Encrypted” or prompt you to turn on encryption. Turning on encryption will take a few hours, and it will need to be plugged in to its charger to do it. You only need to do this once.

## Points as Discussed:

* Disable your GPS reciever by turning off Location Services 
* Turn off Bluetooth, WiFi, and carrier radio by activating Airplane Mode
* Turn back on services you specifically need, like mobile data (re-activates carrier radio)
* Lock screens


## iPhone Setup
Apple has made personal security a priority in recent years, and has provided some iPhone-specific features to make securing your phone easier. These steps below can be used to reasonably secure your phone for an action. 

* Disable your GPS reciever by turning off Location Services 
	* Even in Airplane mode, iOS will keep the GPS receiver active unless you do this.
	* *Settings → Privacy → Location Services*, toggle *Location Services* off.
* Turn off Bluetooth, WiFi, and carrier radio by activating Airplane Mode
* Turn back on services you specifically need, like mobile data (re-activates carrier radio)
* Lock Screen Setup
	* Set your screen to auto-lock as quickly as possible, and require your passcode immediately
		* *Settings → Display & Brightness → Auto-Lock*, set to 30s or 1 minute at the most
		* *Settings → Touch ID & Passcode*, set “Require Passcode” to “Immediately”
	* Practice with iOS’ Emergency SOS mode, and disable the emergency auto-call features.
		* Press and hold the power button and either of the volume buttons until the Emergency SOS lock screen appears. Face ID and Touch ID will be disabled until the passcode is reentered.
		* *Disable Settings → Emergency SOS → Auto-call*
		* *Disable Settings → Emergency SOS → Call with Side Button*
	* Disable Touch ID & Face ID
		* *Settings → Touch ID & Passcode*, under the section “Use Touch ID For:”, toggle all the sliders to off.

For additional protection tips, see our extended document. (link to be added upon publication)

## Android Setup
Android has flexible settings that can be used to make your phone secure and usable in a number of situations. Below are steps to making your phone generally secure for the day of an action.

* Disable your GPS reciever by turning off Location Services 
	* Pull down the notification panel from the top of the screen. There may be a toggle button for Location Services (they often look like a satellite).
	* If you don't have the button in the pulldown, go to *Settings → Location* and turn off "Use location."
* Turn off Bluetooth, WiFi, and carrier radio by activating Airplane Mode
	* Pull down the notification panel from the top of the screen. There may be a toggle button for Airplane Mode (it often look like an airplane). Ensure Airplane Mode is ON.
	* If you don't have the button in the pulldown, go to *Settings → Network & internet* and turn on "Airplane mode."
	* You can turn mobile data back on without leaving airplane mode if you need it. Press the Mobile Data button in the notification panel after you activate Airplane Mode. Those two buttons are often next to each other.
	* Check that Bluetooth is really off. Android may keep it on of bluetooh devices are connected. The button in the notification panel should be grayed/uncolored to indicate it is off. 
* Lock Screen Setup
	* Go to *Settings → Security → Screen lock* and select PIN or Password.
	* You will be asked if you want notifications to be shown on screen while the phone is locked. The safest option is “Don’t show any notifications at all.” If that does not work for you, choose “Hide sensitive notification content.”
	* Click the gear to enter Screen lock settings: 
		* Set "Lock after screen timeout" to Immediately.
		* Turn on "Power button instantly locks"
	* Disable Smart Lock, if you have it. It can keep your phone unlocked when you don't expect it, which is dangerous at an action.
* Go to *Settings → Display → Advanced → Screen timeout* and set it to the shortest possible time, usually 15 seconds.

For additional protection tips, see our extended document. (link to be added upon publication)

# Security Ideas
This section is about keeping your information private in the rest of your life. In this document, “private” means only accessible to you, and not to other entities without your permission.

## Messaging with Encryption
To encrypt your personal communication (like messages with other people), you want *end-to-end* encryption. Many apps claim “encryption” but only a few truly guarantee that your information stays encrypted all the way to your recipient’s phone. The “end-to-end” means it is only readable by you and your recipient. Without the “end-to-end” property, copies of messages may be sent through and saved on a central server, which the provider company has full access to.

## Password Safety

The password is the primary mechanism used to secure your online accounts, but it is also a significant point of vulnerability. How can we manage this? 

* Turn on two-factor authentication (2FA) everywhere it’s offered. 
* Use long and strong passwords that are not easily guessed. 

## Two-Factor Authentication (2FA) 
This adds a second check, whenever you log in, that it’s really you. The second factor can be an app on your phone, text message, or email. A one-time-use code is sent to you which you then enter into the service to prove you control that second factor. Not all channels are equal in their security, but **any 2FA is worlds better than none at all.**

When choosing a 2FA method, an authenticator app such as Google Authenticator ([Android](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2), [iOS](https://apps.apple.com/us/app/google-authenticator/id388497605)) provides a good balance between convenience and security. If more security is desired, physical tokens such as the [Yubikey](https://www.yubico.com/products/) can be used, and the [Yubico Authenticator](https://www.yubico.com/products/services-software/download/yubico-authenticator/) can use the physical tokens to generate one-time codes.

If neither of the above options are available for your service, you might be able to use your email or phone (via SMS) to receive one-time codes. These are not as secure as the above options but, as stated above, any 2FA is worlds better than none at all.

## Strong Passwords
Longer passwords are harder to break, regardless of the types of characters they contain. Modern hackers’ tools can try every possible character in every order for an 8-character password instantly, but a 10-character password would take hours. XKCD did a fun explanation of this: https://xkcd.com/936/

**Your passwords should be easy for you to remember, but too long for a hacker to guess.** The best technique right now is to use a passphrase of multiple words that are easy for you to remember, but so long that it would take centuries for a hacker to crack. You can use a technique called [Diceware](https://en.wikipedia.org/wiki/Diceware) to come up with a random, but memorable passphrase. Doug Muth built a nice online Diceware tool, below.

Diceware Password Generator: https://diceware.dmuth.org/

**Don’t use the same password for multiple accounts.**

## Security Questions 
Personal questions are often used by services as a backup system should you need to reset your password. These questions often ask for personal information, like the name of your childhood pet or mother’s maiden name. This information, however, is often accessible to others.  
When you respond to security questions, try **using code phrases instead of answering them honestly**, so that nobody familiar with your life could guess it and force a password reset without your consent. For instance, for the question “Where did you attend school in the sixth grade?” you could instead respond with your favorite cartoon character from the sixth grade.

# Other Tips
* Think carefully about who you can safely share your involvement in activism with.
* Don’t use email for protest related conversation.
* [Ditch Chrome.](https://www.washingtonpost.com/technology/2019/06/21/google-chrome-has-become-surveillance-software-its-time-switch/) Use Firefox or Brave.
* Don’t use the built-in cloud backup solutions for Android or iOS. 
	* The most secure data backup is the one you make over a USB cable.
* Google your full name occasionally and see what comes up. 
